name: PyInstaller

on:
  push:
    branches:
      - master
      - 3-build-binary-distributions

    tags:
      - 'v[0-9].*'

jobs:
  briefcase:
    name: Bundle on ${{ matrix.os }} / ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.10"]
      fail-fast: false
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install Python libs
        run: |
          python -m pip install --upgrade pip
          pip install -e.[dist]

      - name: ${{matrix.os}} Build
        run: |
          python build.py


      - name: Upload Artifact for Windows
        uses: actions/upload-artifact@v2
        if: runner.os == 'windows-latest'
        with:
          name: cocktail-${{ github.ref_name }}-${{ matrix.os }}.exe
          path: 'dist/cocktail.exe'

      - name: Upload Artifact for Ubuntu
        uses: actions/upload-artifact@v2
        if: runner.os == 'ubuntu-latest'
        with:
          name: cocktail-${{ github.ref_name }}-${{ matrix.os }}
          path: 'dist/cocktail'
