name: PyInstaller

on:
  push:
    branches:
      - master
      - 3-build-binary-distributions

    tags:
      - 'v[0-9].*'

jobs:
  briefcase:
    name: Bundle on ${{ matrix.os }} / ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.10"]
      fail-fast: false
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Install Python
        uses: actions/setup-python@v4.7.1
        with:
          python-version: "3.10"

      - name: Install Python libs
        run: |
          python -m pip install --upgrade pip
          pip install -e.[dist]

      - name: ${{matrix.os}} Build
        run: |
          python build.py --dist

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/cocktail
            dist/cocktail.exe
          tag_name: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
